##################################################################################
## gmbH Project
##################################################################################


max_services_per_node = 3

##################################################################################
[core]
##################################################################################
# 
mode = "local"
#
# Print coreData to stdout and stdErr? This can be overriden with the --verbose 
# command line flag
verbose = true
#
# For instances where gmbh is running in a container
daemom = false
#
# The address to start the coreData server
address = "localhost:49500" #default is localhost:49500
#
# How long between keep alive messages
keep_alive = "45s"
#
# Path to gmbhCore binary
core_bin = ""   # default is $GOPATH/bin/gmbhCore
                # Note cannot interpolate env vars in TOML

##################################################################################
[procm]
##################################################################################
# What address should the ProcM be started at
address = "localhost:5900" #default is localhost:59500
#
# How long between keep alive messages
keep_alive = "45s"
#
# Print gmbhProcM to stdout and stdErr
verbose = false
#
# Path to gmbhProcm binary
procm_bin = ""  # default is $GOPATH/bin/gmbhProcm
                # Note cannot interpolate env vars in TOML


##################################################################################
[services] # Holds the array of services to launch from the service launcher and
############ start in managed mode.
##################################################################################

    ## The data needed to start each service
    #
    # Note that either a language and src_path need to be specifed or a bin_path needs
    # to be specified for the service launcher to successfully start the service.
    [[service]]
    # A name to give the services
    id = ""
    #
    # Arguments that will be passed on to the service
    args = [""]
    #
    # Environemnt Variables that will be passed on to the service
    env = [""]
    #
    # The language(python|go|node) the service is written in. 
    language = ""
    #
    # If a bin path is supplied it will be used to launch the service
    bin_path = ""
    #
    # If a src path is supplied it will be used to build the service at launch time
    # NOTE: For Go projects -- Specify a path that will be able to be started using
    #       *.go (with *_test.go filtered out)
    src_path = ""
    #
    # If this service will require a port to be opened, specify it here.
    ports = [""]
